import { Inter } from "next/font/google";
import "./globals.css";
import connect from "../dbconnect";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connect();
  return (
    <html lang="en" className="h-full">
      <body style={{backgroundImage : "url(bg.jpg)", backgroundRepeat : "no-repeat", backgroundSize : "cover", backdropFilter : "blur(2px)"}} className = "h-full">{children}</body>
    </html>
  );
}
